#!/bin/bash

LOOP=0
center_box &
# lecho "BEFORE_EDIT_INI_GUI SIGNAL_CODE: ${SIGNAL_CODE}"
# lecho "BEFORE_CHECK_INI_FILE INI_FILE_DIR_PATH: ${INI_FILE_DIR_PATH}"
# lecho "BEFORE_CHECK_INI_FILE EXECUTE_FILE_NAME: ${EXECUTE_FILE_NAME}"
# lecho "BEFORE_CHECK_INI_FILE EDIT_FILE_PATH: ${EDIT_FILE_PATH}"
INDEX_TITLE_TEXT_MESSAGE=${EDIT_CMD_INDEX_MESSAGE}
EDIT_FILE_PATH="${INI_FILE_DIR_PATH}/${EXECUTE_FILE_NAME}"
check_ini_file "${EDIT_FILE_PATH}"
case "${SIGNAL_CODE}" in 
	"${CHECK_ERR_CODE}") SIGNAL_CODE=${INDEX_CODE};;
esac
case "${SIGNAL_CODE}" in 
	"${INDEX_CODE}") continue;;
esac

# lecho "BEFORE_EDIT_INI_GUI EXECUTE_FILE_NAME: ${EXECUTE_FILE_NAME}"
EDIT_EDITOR_ON=""
wait
edit_ini_gui "${EXECUTE_FILE_NAME}"
SIGNAL_CODE=${INDEX_CODE}
# lecho "AFTER_EDIT_INI_GUI SIGNAL_CODE: ${SIGNAL_CODE}"