#!/bin/bash

set -e


kill_all_process(){
	ps aux \
	| awk '(\
			$0 ~ "cmdclick" \
				&& $0 !~ "grep" \
		){ 
			printf $2"\t"
		}' \
	| kill $(cat)
}


first_option="${1:-}"
case "${first_option}" in
	"-k") 
		kill_all_process
		exit 0
		;;
	"") 
		exec_cmdclick_path="$(dirname $0)/win/srcs/cmdclick_dir/exec_cmdclick.sh"
		bash "${exec_cmdclick_path}"
		exit 0
		;;
esac
exec_cmdclick_path="$(dirname $0)/win/srcs/cmdclick_dir/exec_cmdclick.sh"
bash "${exec_cmdclick_path}" "${first_option}"
