#!/bin/bash

set -e


kill_all_process(){
	ps aux \
	| awk '(\
			$0 ~ "cmdclick" \
				&& $0 !~ "grep" \
		){ 
			printf $2"\t"
		}' \
	| kill $(cat)
}


first_option="${1}"
case "${first_option}" in
	"") 
		bash "$(dirname $0)/win/srcs/cmdclick_dir/exec_cmdclick.sh"
		exit 0
esac

kill_all_process