#!/bin/bash


# lecho "BEFORE_CREATE_ADD_COMMAND_FORM SIGNAL_CODE: ${SIGNAL_CODE}"
CHDIR_LOOP=0
CREATE_CHDIR_PATH=""
CMD_CLICK_ADD_TITLE="${ADD_CD_PATH_MESSAGE}"
create_chdir_command_form
# lecho "BEFORE_CREATE_ADD_COMMAND_FORM SIGNAL_CODE: ${SIGNAL_CODE}"
# lecho "CREATE_CHDIR_PATH: ${CREATE_CHDIR_PATH}"
if [ -n "${CREATE_CHDIR_PATH}" ];then SIGNAL_CODE=${OK_CODE};
else SIGNAL_CODE=${EXIT_CODE};fi
# lecho "SIGNAL_CODE: ${SIGNAL_CODE}"
# lecho "${CREATE_CHDIR_PATH}"
if [ ${SIGNAL_CODE} -eq ${OK_CODE} ]; then
	# lecho "BEFORE_ADD_CMD_INI_FILE CREATE_CHDIR_PATH: ${CREATE_CHDIR_PATH}"
	# lecho "BEFORE_ADD_CMD_INI_FILE INI_FILE_DIR_PATH: ${INI_FILE_DIR_PATH}"
	add_chdir_cmd_ini_file "${CREATE_CHDIR_PATH}"
elif [ ${SIGNAL_CODE} -eq ${EXIT_CODE} ] || [ ${SIGNAL_CODE} -ge ${FORCE_EXIT_CODE} ]; then
	:
fi
SIGNAL_CODE=${INDEX_CODE}
# lecho "AFTER_ADD_CMD_INI_FILE SIGNAL_CODE: ${SIGNAL_CODE}"
